version: '3'
services:
  flask-app:
    build: .
    ports:
      - '8083:8083'  # Map external 8083 to internal 8083
    depends_on:
      - mongo
    networks:
      - mynetwork
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - mynetwork

networks:
  mynetwork:
