apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my_pro-flask-app  # Match the labels in your Deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083  # Update targetPort to match your app's port
  type: LoadBalancer
